apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  replicas: 1
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
      - name: dispatcher-service
        image: dispatcher-service
        imagePullPolicy: Never
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        ports:
        - containerPort: 9003